datasets:
  rotation:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    #grid
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets/grid_train.json
        val:
          storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets/grid_val.json
        test:
          storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets/grid_test.json
      images:
        storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets
        train:
          storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets/train
        val:
          storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets/val
        test:
          storage: /home/user/project/InstructBLIP_PEFT/input/rotation/grid_rotated_datasets/test